version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pair-consistency-expansive-homomorphism:1.0
    container_name: pair-consistency-expansive-homomorphism
    environment:
      .env_file: .app.env
      TZ: America/Indiana/Indianapolis
      PYTHONUNBUFFERED: 1
    volumes:
      - ./output:/app/output
      - ./gurobi.lic:/opt/gurobi/gurobi.lic:ro
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 5GB
        reservations:
          memory: 2GB